insert into bible_db.bible_rv60_books (id, name, abreviation, testament, genre)
values  (1, 'Génesis', 'Gn', 'O', ''),
        (2, 'Éxodo', 'Ex', 'O', ''),
        (3, 'Levítico', 'Lv', 'O', ''),
        (4, 'Números', 'Nm', 'O', ''),
        (5, 'Deuteronomio', 'Dt', 'O', ''),
        (6, 'Josué', 'Jos', 'O', ''),
        (7, 'Jueces', 'Jue', 'O', ''),
        (8, 'Rut', 'Rt', 'O', ''),
        (9, '1 Samuel', '1 S', 'O', ''),
        (10, '2 Samuel', '2 S', 'O', ''),
        (11, '1 Reyes', '1 R', 'O', ''),
        (12, '2 Reyes', '2 R', 'O', ''),
        (13, '1 Crónicas', '1 Cr', 'O', ''),
        (14, '2 Crónicas', '2 Cr', 'O', ''),
        (15, 'Esdras', 'Esd', 'O', ''),
        (16, 'Nehemías', 'Neh', 'O', ''),
        (17, 'Ester', 'Est', 'O', ''),
        (18, 'Job', 'Job', 'O', ''),
        (19, 'Salmos', 'Sal', 'O', ''),
        (20, 'Proverbios', 'Pr', 'O', ''),
        (21, 'Eclesiastés', 'Ec', 'O', ''),
        (22, 'Cantares', 'Cnt', 'O', ''),
        (23, 'Isaías', 'Is', 'O', ''),
        (24, 'Jeremías', 'Jer', 'O', ''),
        (25, 'Lamentaciones', 'Lm', 'O', ''),
        (26, 'Ezequiel', 'Ez', 'O', ''),
        (27, 'Daniel', 'Dn', 'O', ''),
        (28, 'Oseas', 'Os', 'O', ''),
        (29, 'Joel', 'Jl', 'O', ''),
        (30, 'Amós', 'Am', 'O', ''),
        (31, 'Abdías', 'Abd', 'O', ''),
        (32, 'Jonás', 'Jon', 'O', ''),
        (33, 'Miqueas', 'Mi', 'O', ''),
        (34, 'Nahúm', 'Nah', 'O', ''),
        (35, 'Habacuc', 'Hab', 'O', ''),
        (36, 'Sofonías', 'Sof', 'O', ''),
        (37, 'Hageo', 'Hag', 'O', ''),
        (38, 'Zacarías', 'Zac', 'O', ''),
        (39, 'Malaquías', 'Mal', 'O', ''),
        (40, 'Mateo', 'Mt', 'N', ''),
        (41, 'Marcos', 'Mr', 'N', ''),
        (42, 'Lucas', 'Lc', 'N', ''),
        (43, 'Juan', 'Jn', 'N', ''),
        (44, 'Hechos', 'Hch', 'N', ''),
        (45, 'Romanos', 'Ro', 'N', ''),
        (46, '1 Corintios', '1 Co', 'N', ''),
        (47, '2 Corintios', '2 Co', 'N', ''),
        (48, 'Gálatas', 'Ga', 'N', ''),
        (49, 'Efesios', 'Ef', 'N', ''),
        (50, 'Filipenses', 'Fil', 'N', ''),
        (51, 'Colosenses', 'Col', 'N', ''),
        (52, '1 Tesalonicenses', '1 Ts', 'N', ''),
        (53, '2 Tesalonicenses', '2 Ts', 'N', ''),
        (54, '1 Timoteo', '1 Ti', 'N', ''),
        (55, '2 Timoteo', '2 Ti', 'N', ''),
        (56, 'Tito', 'Tit', 'N', ''),
        (57, 'Filemón', 'Flm', 'N', ''),
        (58, 'Hebreos', 'He', 'N', ''),
        (59, 'Santiago', 'Stg', 'N', ''),
        (60, '1 Pedro', '1 P', 'N', ''),
        (61, '2 Pedro', '2 P', 'N', ''),
        (62, '1 Juan', '1 Jn', 'N', ''),
        (63, '2 Juan', '2 Jn', 'N', ''),
        (64, '3 Juan', '3 Jn', 'N', ''),
        (65, 'Judas', 'Jud', 'N', ''),
        (66, 'Apocalipsis', 'Ap', 'N', '');